version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000